const words = [
    "Train",
    "Rain",
    "Snowman",
    "Happiness",
    "Sun",
    "Computer",
    "Phone",
    "Bug",
    "Dark",
    "Moon",
    "Desk",
    "Pay cheque",
    "Phone",
    "Paper",
    "Light",
    "Chair",
    "Desk lamp",
    "Notepad",
    "Paper clips",
    "Calculator",
    "Calendar",
    "Sticky notes",
    "Pens",
    "Pencils",
    "Notebook",
    "Book",
    "Chairs",
    "Coffee cup",
    "Coffee mug",
    "Glue",
    "Clipboard",
    "Paperclips",
    "Chocolate",
    "Secretary",
    "Work",
    "Paperwork",
    "Workload",
    "Employee",
    "Boredom",
    "Coffee",
    "Golf",
    "Laptop",
    "Sandcastle",
    "Monday",
    "Vanilla",
    "Sneeze",
    "Scratch",
    "Celery",
    "Hammer",
    "Frog",
    "Tennis",
    "Hot dog",
    "Pants",
    "Bridge",
    "Bubblegum",
    "Candy bar",
    "Bucket",
    "Skiing",
    "Sledding",
    "Snowboarding",
    "Snowman",
    "Polar Bear",
    "Cream",
    "Waffle",
    "Pancakes",
    "Ice cream",
    "Sundae",
    "Beach",
    "Sunglasses",
    "Surfboard",
    "Watermelon",
    "Baseball",
    "Bat",
    "Ball",
    "T-shirt",
    "Kiss",
    "Jellyfish",
    "Jelly",
    "Butterfly",
    "Spider",
    "Broom",
    "Spiderweb",
    "Mummy",
    "Candy",
    "Bats",
    "Squirrels",
    "Basketball",
    "Water bottle",
    "Unicorn",
    "Dog leash",
    "Newspaper",
    "Hammock",
    "Video camera",
    "Money",
    "miley face",
    "umbrella",
    "picnic basket",
    "teddy bear",
    "ambulance",
    "pyramid",
    "bacteria",
    "Pizza",
    "Goldfish bowl",
    "Skull",
    "Spider web",
    "Smoke",
    "Tree",
    "Ice",
    "Blanket",
    "Seaweed",
    "Flame",
    "Bubble",
    "Hair",
    "Tooth",
    "Leaf",
    "Worm",
    "Sky",
    "Apple",
    "Plane",
    "Cow",
    "House",
    "Dog",
    "Car",
    "Bed",
    "Furniture",
    "Train",
    "Rainbow",
    "Paintings",
    "Drawing",
    "Cup",
    "Plate",
    "Bowl",
    "Cushion",
    "Sofa",
    "Sheet",
    "Kitchen",
    "Table",
    "Candle",
    "Shirt",
    "Clothes",
    "Dress",
    "Pillow",
    "Home",
    "Toothpaste",
    "Guitar",
    "Schoolbag",
    "Pencil Case",
    "Glasses",
    "Towel",
    "Watch",
    "Piano",
    "Pen",
    "Hat",
    "Shoes",
    "Socks",
    "Jeans",
    "Hair Gel",
    "Keyboard",
    "Bra",
    "Jacket",
    "Tie",
    "Bandage",
    "Scarf",
    "Hair Brush",
    "Cell Phone",
];

const wordsSLO = [
    "Vlak",
    "Dežnik",
    "Snežak",
    "Veselje",
    "Sonce",
    "Računalnik",
    "Telefon",
    "Hrošč",
    "Tema",
    "Luna",
    "Miza",
    "Čakalna vrsta",
    "Papir",
    "Svetloba",
    "Stol",
    "Namizna svetilka",
    "Zvezek",
    "Sponka za papir",
    "Kalkulator",
    "Koledar",
    "Pisala",
    "Knjiga",
    "Stol",
    "Lepilo",
    "Vrt",
    "Čokolada",
    "Tajnica",
    "Delo",
    "Zaposleni",
    "Dolgčas",
    "Kava",
    "Golf",
    "Prenosni Računalnik",
    "Grad",
    "Ponedeljek",
    "Vanilija",
    "Kihanje",
    "Praska",
    "Žaba",
    "Tenis",
    "Hot dog",
    "Hlače",
    "Most",
    "Balon",
    "Bombon",
    "Košara",
    "Smučanje",
    "Bordanje",
    "Polarni medved",
    "Smetana",
    "Palačinke",
    "Sladoled",
    "Plaža",
    "sončna očala",
    "Lubenica",
    "Nogomet",
    "Netopir",
    "Žoga",
    "Uhan",
    "Poljub",
    "Riba",
    "Želatina",
    "Metulj",
    "Pajek",
    "Pajkova mreža",
    "Mumija",
    "Krava",
    "Veverica",
    "zapestnica",
    "plastenka",
    "deževnik",
    "Pasja ovratnica",
    "novice",
    "Kamera",
    "Denar",
    "Sreča",
    "Dežnik",
    "plišast medvedek",
    "Gasilci",
    "piramida",
    "bakterija",
    "Pizza",
    "akvarij",
    "Lobanja",
    "Dim",
    "Drevo",
    "Led",
    "Koca",
    "ogenj",
    "mehurček",
    "lasje",
    "zob",
    "Kruh",
    "Nebo",
    "Jabolko",
    "Letalo",
    "Hiša",
    "Pes",
    "Mačka",
    "Postelja",
    "pohištvo",
    "Mavrica",
    "Slika",
    "Posoda",
    "Krožnik",
    "muha",
    "Tla",
    "Kuhinja",
    "Miza",
    "Sveča",
    "Oblačila",
    "Krilo",
    "Blazina",
    "Dom",
    "Zobna pasta",
    "Kitara",
    "Šolska torba",
    "Steklo",
    "Robček",
    "Ura",
    "Klavir",
    "Kapa",
    "Čevlji",
    "Tipkovnica",
    "Jakna",
    "Kravata",
    "Šal",
    "Glavnik",
];

module.exports = {words};